# -*- coding: utf-8 -*-
"""ddos_detector

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gjJPS73jiFJGAnJN-jHDklxBIEJz2uxC
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv2D, Flatten, MaxPooling2D, Dropout

# ==========================================
# Configuration
# ==========================================
DATASET_PATH = "Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv"
IMG_SIZE = 9  # We will reshape 78 features into a 9x9 image (81 pixels)
              # 78 features + 3 padding zeros = 81
BATCH_SIZE = 64
EPOCHS = 5

def load_and_preprocess_data(filepath):
    """
    Loads CSV data, cleans it, and scales features to [0, 1].
    """
    print(f"[INFO] Loading dataset from {filepath}...")
    df = pd.read_csv(filepath)

    # 1. Clean Column Names (remove spaces)
    df.columns = df.columns.str.strip()

    # 2. Handle Missing/Infinite Values
    # Replace infinite values with NaN and drop them
    df.replace([np.inf, -np.inf], np.nan, inplace=True)
    df.dropna(inplace=True)

    print(f"[INFO] Data Shape after cleaning: {df.shape}")

    # 3. Encode Labels
    # 'BENIGN' -> 0, 'DDoS' -> 1
    df['Label'] = df['Label'].apply(lambda x: 0 if x == 'BENIGN' else 1)

    # Separate features and target
    y = df['Label'].values
    X = df.drop(columns=['Label'])

    # 4. Scale Features to [0, 1]
    # This is crucial for image conversion so pixel values are valid
    scaler = MinMaxScaler()
    X_scaled = scaler.fit_transform(X)

    return X_scaled, y

def convert_to_images(X_data, img_size=9):
    """
    Reshapes the 1D feature vectors into 2D images.
    Input shape: (N, 78)
    Output shape: (N, 9, 9, 1)
    """
    print("[INFO] Converting network flows to images...")
    n_samples = X_data.shape[0]
    n_features = X_data.shape[1]

    # Calculate required padding
    target_size = img_size * img_size
    padding_needed = target_size - n_features

    if padding_needed > 0:
        # Pad with zeros at the end of the vector
        padding = np.zeros((n_samples, padding_needed))
        X_padded = np.hstack((X_data, padding))
    else:
        # Trim if we had too many features (unlikely here)
        X_padded = X_data[:, :target_size]

    # Reshape to (N, H, W, Channels)
    # Grayscale image, so Channels = 1
    X_images = X_padded.reshape(n_samples, img_size, img_size, 1)

    return X_images

def build_cnn_model(input_shape):
    """
    Defines the Convolutional Neural Network architecture.
    """
    model = Sequential([
        # Convolutional Layer: Extracts spatial features
        Conv2D(32, kernel_size=(3, 3), activation='relu', input_shape=input_shape),

        # Max Pooling: Reduces dimensionality
        MaxPooling2D(pool_size=(2, 2)),

        # Flatten: Converts 2D matrix back to vector for the dense layers
        Flatten(),

        # Dense Layers: Classification
        Dense(64, activation='relu'),
        Dropout(0.5), # Regularization
        Dense(1, activation='sigmoid') # Binary Output (DDoS vs Benign)
    ])

    model.compile(optimizer='adam',
                  loss='binary_crossentropy',
                  metrics=['accuracy'])

    return model

def visualize_sample(X_images, y, index=0):
    """
    Helper to save a sample converted image to disk for inspection.
    """
    plt.figure(figsize=(4, 4))
    plt.imshow(X_images[index].reshape(9, 9), cmap='gray')
    label = "DDoS" if y[index] == 1 else "BENIGN"
    plt.title(f"Network Flow as Image\nLabel: {label}")
    plt.axis('off')
    plt.savefig(f"sample_flow_{index}.png")
    print(f"[INFO] Saved sample image to sample_flow_{index}.png")

def main():
    # 1. Prepare Data
    X_scaled, y = load_and_preprocess_data(DATASET_PATH)

    # 2. Convert to Images
    X_images = convert_to_images(X_scaled, IMG_SIZE)

    # Save a sample image to see what it looks like
    visualize_sample(X_images, y, index=10)

    # 3. Split Data
    X_train, X_test, y_train, y_test = train_test_split(
        X_images, y, test_size=0.2, random_state=42
    )

    print(f"[INFO] Training Set: {X_train.shape}")
    print(f"[INFO] Testing Set: {X_test.shape}")

    # 4. Build and Train Model
    model = build_cnn_model(input_shape=(IMG_SIZE, IMG_SIZE, 1))
    model.summary()

    print("[INFO] Starting Training...")
    history = model.fit(
        X_train, y_train,
        epochs=EPOCHS,
        batch_size=BATCH_SIZE,
        validation_split=0.1
    )

    # 5. Evaluate
    print("[INFO] Evaluating on Test Set...")
    loss, accuracy = model.evaluate(X_test, y_test)
    print(f"\n[RESULT] Test Accuracy: {accuracy * 100:.2f}%")

    # 6. Save Model
    model.save("ddos_cnn_model.h5")
    print("[INFO] Model saved as 'ddos_cnn_model.h5'")

if __name__ == "__main__":
    main()
