# -*- coding: utf-8 -*-
"""ddos_interactive

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rztyUjHOFTHNu5ZF2TBbdj7yvL7NzFMR
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import random
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
import tensorflow as tf
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Dense, Conv2D, Flatten, MaxPooling2D, Dropout, Input

# ==========================================
# Configuration
# ==========================================
DATASET_PATH = "Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv"
MODEL_PATH = "ddos_cnn_model.keras"  # Updated to new Keras format
IMG_SIZE = 9
BATCH_SIZE = 64
EPOCHS = 5

def load_and_preprocess_data(filepath):
    """Loads and cleans the dataset."""
    if not os.path.exists(filepath):
        print(f"[ERROR] File not found: {filepath}")
        return None, None

    print(f"\n[INFO] Loading dataset from {filepath}...")
    df = pd.read_csv(filepath)
    df.columns = df.columns.str.strip()
    df.replace([np.inf, -np.inf], np.nan, inplace=True)
    df.dropna(inplace=True)

    # Label Encoding
    df['Label'] = df['Label'].apply(lambda x: 0 if x == 'BENIGN' else 1)

    y = df['Label'].values
    X = df.drop(columns=['Label'])

    # Scale Features
    scaler = MinMaxScaler()
    X_scaled = scaler.fit_transform(X)

    return X_scaled, y

def convert_to_images(X_data, img_size=9):
    """Reshapes 1D vectors into 2D images."""
    n_samples = X_data.shape[0]
    n_features = X_data.shape[1]
    target_size = img_size * img_size

    # Pad if necessary
    padding_needed = target_size - n_features
    if padding_needed > 0:
        padding = np.zeros((n_samples, padding_needed))
        X_padded = np.hstack((X_data, padding))
    else:
        X_padded = X_data[:, :target_size]

    # Reshape
    X_images = X_padded.reshape(n_samples, img_size, img_size, 1)
    return X_images

def train_model():
    """Trains the CNN model and saves it."""
    X_scaled, y = load_and_preprocess_data(DATASET_PATH)
    if X_scaled is None: return

    X_images = convert_to_images(X_scaled, IMG_SIZE)

    # Split
    X_train, X_test, y_train, y_test = train_test_split(X_images, y, test_size=0.2, random_state=42)

    # Build Model
    model = Sequential([
        Input(shape=(IMG_SIZE, IMG_SIZE, 1)),
        Conv2D(32, kernel_size=(3, 3), activation='relu'),
        MaxPooling2D(pool_size=(2, 2)),
        Flatten(),
        Dense(64, activation='relu'),
        Dropout(0.5),
        Dense(1, activation='sigmoid')
    ])

    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

    print("\n[INFO] Starting Training...")
    model.fit(X_train, y_train, epochs=EPOCHS, batch_size=BATCH_SIZE, validation_split=0.1)

    print("\n[INFO] Evaluating on Test Set...")
    loss, accuracy = model.evaluate(X_test, y_test)
    print(f"\n[RESULT] Test Accuracy: {accuracy * 100:.2f}%")

    model.save(MODEL_PATH)
    print(f"[INFO] Model saved as '{MODEL_PATH}'")

def test_random_sample():
    """Loads model and predicts on a random sample from the dataset."""
    if not os.path.exists(MODEL_PATH):
        print(f"[ERROR] Model file '{MODEL_PATH}' not found. Please train first.")
        return

    print("\n[INFO] Loading Model...")
    model = load_model(MODEL_PATH)

    # Load data specifically to pick a random sample
    X_scaled, y = load_and_preprocess_data(DATASET_PATH)
    if X_scaled is None: return

    # Pick random index
    idx = random.randint(0, len(X_scaled) - 1)
    sample_vector = X_scaled[idx].reshape(1, -1)
    true_label = "DDoS" if y[idx] == 1 else "BENIGN"

    # Convert single sample to image
    sample_image = convert_to_images(sample_vector, IMG_SIZE)

    # Predict
    prediction_prob = model.predict(sample_image)[0][0]
    predicted_label = "DDoS" if prediction_prob > 0.5 else "BENIGN"
    confidence = prediction_prob if prediction_prob > 0.5 else 1 - prediction_prob

    print(f"\n--- Random Sample Analysis (Index {idx}) ---")
    print(f"True Label:      {true_label}")
    print(f"Predicted Label: {predicted_label}")
    print(f"Confidence:      {confidence * 100:.2f}%")

    # Show Image
    plt.imshow(sample_image[0].reshape(9, 9), cmap='gray')
    plt.title(f"Network Flow Image\nTrue: {true_label} | Pred: {predicted_label}")
    plt.axis('off')
    plt.show()
    print("[INFO] Image displayed.")

def main():
    while True:
        print("\n=== DDoS Detection System ===")
        print("1. Train New Model")
        print("2. Load Model & Test Random Sample")
        print("3. Exit")
        choice = input("Select option (1-3): ")

        if choice == '1':
            train_model()
        elif choice == '2':
            test_random_sample()
        elif choice == '3':
            print("Exiting...")
            break
        else:
            print("Invalid choice.")

if __name__ == "__main__":
    main()
